#ifndef OBNEXPORTSEGY_GLOBAL_H
#define OBNEXPORTSEGY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OBNEXPORTSEGY_LIBRARY)
#define OBNEXPORTSEGY_EXPORT Q_DECL_EXPORT
#else
#define OBNEXPORTSEGY_EXPORT Q_DECL_IMPORT
#endif

#endif // OBNEXPORTSEGY_GLOBAL_H
