#ifndef OBNREALTIMEWAVEFORMDISPLAY_GLOBAL_H
#define OBNREALTIMEWAVEFORMDISPLAY_GLOBAL_H

#include <QtCore/qglobal.h>
//#define OBNREALTIMEWAVEFORMDISPLAY_LIBRARY

#ifdef OBNREALTIMEWAVEFORMDISPLAY_LIBRARY
#define OBNREALTIMEWAVEFORMDISPLAY_EXPORT Q_DECL_EXPORT
#else
#define OBNREALTIMEWAVEFORMDISPLAY_EXPORT Q_DECL_IMPORT
#endif

#endif // OBNREALTIMEWAVEFORMDISPLAY_GLOBAL_H
