#ifndef OBNJOBMONITORPROGRAME_GLOBAL_H
#define OBNJOBMONITORPROGRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OBNJOBMONITORPROGRAME_LIBRARY)
#define OBNJOBMONITORPROGRAME_EXPORT Q_DECL_EXPORT
#else
#define OBNJOBMONITORPROGRAME_EXPORT Q_DECL_IMPORT
#endif

#endif // OBNJOBMONITORPROGRAME_GLOBAL_H
