#ifndef OBNRETRIEVEAVAILABLENODES_GLOBAL_H
#define OBNRETRIEVEAVAILABLENODES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OBNRETRIEVEAVAILABLENODES_LIBRARY)
#define OBNRETRIEVEAVAILABLENODES_EXPORT Q_DECL_EXPORT
#else
#define OBNRETRIEVEAVAILABLENODES_EXPORT Q_DECL_IMPORT
#endif

#endif // OBNRETRIEVEAVAILABLENODES_GLOBAL_H
