#ifndef OBNLMGRAREALISTWIDGET_GLOBAL_H
#define OBNLMGRAREALISTWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OBNLMGRAREALISTWIDGET_LIBRARY)
#define OBNLMGRAREALISTWIDGET_EXPORT Q_DECL_EXPORT
#else
#define OBNLMGRAREALISTWIDGET_EXPORT Q_DECL_IMPORT
#endif

#endif // OBNLMGRAREALISTWIDGET_GLOBAL_H
