#ifndef OBNCALIBRATIONDATADISPLAY_GLOBAL_H
#define OBNCALIBRATIONDATADISPLAY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OBNCALIBRATIONDATADISPLAY_LIBRARY)
#define OBNCALIBRATIONDATADISPLAY_EXPORT Q_DECL_EXPORT
#else
#define OBNCALIBRATIONDATADISPLAY_EXPORT Q_DECL_IMPORT
#endif

#endif // OBNCALIBRATIONDATADISPLAY_GLOBAL_H
