#ifndef OBNDISPLAYSEGY_GLOBAL_H
#define OBNDISPLAYSEGY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OBNDISPLAYSEGY_LIBRARY)
#define OBNDISPLAYSEGY_EXPORT Q_DECL_EXPORT
#else
#define OBNDISPLAYSEGY_EXPORT Q_DECL_IMPORT
#endif

#endif // OBNDISPLAYSEGY_GLOBAL_H
