#ifndef OBNLOGVISUAILZATIONDISP_GLOBAL_H
#define OBNLOGVISUAILZATIONDISP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OBNLOGVISUAILZATIONDISP_LIBRARY)
#define OBNLOGVISUAILZATIONDISP_EXPORT Q_DECL_EXPORT
#else
#define OBNLOGVISUAILZATIONDISP_EXPORT Q_DECL_IMPORT
#endif

#endif // OBNLOGVISUAILZATIONDISP_GLOBAL_H
